const matchedData = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    city: "Malibu",
    location: "Malibu beachfront, Malibu",
    country: "United States",
    latitude: 34.0259,
    longitude: -118.7798,
    category: "Trending",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    city: "New York",
    location: "Downtown Manhattan, New York City",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    category: "Iconic Cities",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    city: "Aspen",
    location: "Red Mountain area, Aspen",
    country: "United States",
    latitude: 39.1911,
    longitude: -106.8175,
    category: "Hill Stations",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    city: "Florence",
    location: "Tuscan countryside near Florence",
    country: "Italy",
    latitude: 43.7696,
    longitude: 11.2558,
    category: "Trending",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    city: "Portland",
    location: "Forest Park treeline, Portland",
    country: "United States",
    latitude: 45.5152,
    longitude: -122.6784,
    category: "Camping",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    city: "Cancun",
    location: "Hotel Zone, Cancun",
    country: "Mexico",
    latitude: 21.1619,
    longitude: -86.8515,
    category: "Trending",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    city: "South Lake Tahoe",
    location: "Cabin near Lake Tahoe, South Lake Tahoe",
    country: "United States",
    latitude: 39.0968,
    longitude: -120.0324,
    category: "Camping",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTlwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    city: "Los Angeles",
    location: "Downtown Los Angeles",
    country: "United States",
    latitude: 34.0522,
    longitude: -118.2437,
    category: "Iconic Cities",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    city: "Verbier",
    location: "Verbier ski resort",
    country: "Switzerland",
    latitude: 46.0969,
    longitude: 7.2286,
    category: "Hill Stations",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    city: "Serengeti",
    location: "Safari lodge in Serengeti National Park",
    country: "Tanzania",
    latitude: -2.3333,
    longitude: 34.8333,
    category: "Deserts",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    city: "Amsterdam",
    location: "Jordaan canal district, Amsterdam",
    country: "Netherlands",
    latitude: 52.3676,
    longitude: 4.9041,
    category: "Iconic Cities",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    city: "Nadi",
    location: "Private island retreat near Nadi",
    country: "Fiji",
    latitude: -17.7134,
    longitude: 178.065,
    category: "Trending",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    city: "Stow-on-the-Wold",
    location: "Cotswolds countryside near Stow-on-the-Wold",
    country: "United Kingdom",
    latitude: 51.833,
    longitude: -1.8433,
    category: "Farms",
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    city: "Boston",
    location: "Back Bay, Boston",
    country: "United States",
    latitude: 42.3601,
    longitude: -71.0589,
    category: "Iconic Cities",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    city: "Kuta",
    location: "Canggu beachfront, Bali",
    country: "Indonesia",
    latitude: -8.3405,
    longitude: 115.092,
    category: "Trending",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGd1fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    city: "Banff",
    location: "Tunnel Mountain area, Banff",
    country: "Canada",
    latitude: 51.1784,
    longitude: -115.5708,
    category: "Hill Stations",
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGd1fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    city: "Miami Beach",
    location: "South Beach, Miami Beach",
    country: "United States",
    latitude: 25.7617,
    longitude: -80.1918,
    category: "Iconic Cities",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTI8fGxvZGdIfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    city: "Phuket",
    location: "Kamala Beach, Phuket",
    country: "Thailand",
    latitude: 7.8804,
    longitude: 98.3923,
    category: "Amazing Pools",
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTI8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    city: "Inverness",
    location: "Scottish Highlands near Inverness",
    country: "United Kingdom",
    latitude: 57.12,
    longitude: -4.71,
    category: "Castles",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWI8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    city: "Dubai",
    location: "Desert resort outside Dubai",
    country: "United Arab Emirates",
    latitude: 25.2048,
    longitude: 55.2708,
    category: "Deserts",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    city: "Bozeman",
    location: "Cabin near Bozeman, Montana",
    country: "United States",
    latitude: 46.8797,
    longitude: -110.3626,
    category: "Camping",
  },
  {
    title: "Beachfront Villa in Greece",
    description: "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    city: "Mykonos",
    location: "Agios Ioannis area, Mykonos",
    country: "Greece",
    latitude: 37.45,
    longitude: 25.35,
    category: "Trending",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTlwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 750,
    city: "Monteverde",
    location: "Cloud forest near Monteverde",
    country: "Costa Rica",
    latitude: 9.7489,
    longitude: -83.7534,
    category: "Camping",
  },
  {
    title: "Historic Cottage in Charleston",
    description: "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    city: "Charleston",
    location: "Historic District, Charleston",
    country: "United States",
    latitude: 32.7765,
    longitude: -79.9311,
    category: "Trending",
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    city: "Tokyo",
    location: "Shibuya district, Tokyo",
    country: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    category: "Iconic Cities",
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    city: "Meredith",
    location: "Lake Winnipesaukee, Meredith",
    country: "United States",
    latitude: 43.1939,
    longitude: -71.5724,
    category: "Camping",
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 6000,
    city: "Male",
    location: "Overwater villa near Male",
    country: "Maldives",
    latitude: 3.2028,
    longitude: 73.2207,
    category: "Amazing Pools",
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGxha2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    city: "Aspen",
    location: "Snowmass Village, Aspen",
    country: "United States",
    latitude: 39.1911,
    longitude: -106.8175,
    category: "Hill Stations",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    city: "Tamarindo",
    location: "Pacific coast near Tamarindo",
    country: "Costa Rica",
    latitude: 9.7489,
    longitude: -83.7534,
    category: "Trending",
  },
  {
    title: "Marina Bay Skyline Loft",
    description: "Sleek duplex loft with floor-to-ceiling windows looking out over Marina Bay Sands and the Singapore skyline.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=60",
    },
    price: 24000,
    city: "Singapore",
    location: "Marina Bay",
    country: "Singapore",
    latitude: 1.283,
    longitude: 103.86,
    category: "Iconic Cities",
  },
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    },
    price: 1500,
    city: "Malibu",
    location: "Pacific Coast Highway, Malibu",
    country: "United States",
    latitude: 34.0259,
    longitude: -118.7798,
    category: "Trending",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 1200,
    city: "New York",
    location: "Downtown Manhattan",
    country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    category: "Trending",
  },
  {
    title: "Skyline View Penthouse",
    description: "A luxurious penthouse offering sweeping skyline views and premium amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    },
    price: 4000,
    city: "Chicago",
    location: "Magnificent Mile",
    country: "United States",
    latitude: 41.8781,
    longitude: -87.6298,
    category: "Trending",
  },
  {
    title: "Luxury Desert Villa",
    description: "Relax in a stunning desert villa featuring private pools and panoramic views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090",
    },
    price: 5000,
    city: "Dubai",
    location: "Palm Jumeirah",
    country: "United Arab Emirates",
    latitude: 25.2048,
    longitude: 55.2708,
    category: "Trending",
  },
  {
    title: "Parisian Romantic Suite",
    description: "A cozy suite in central Paris with classic interiors and a balcony view of the Eiffel Tower.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    },
    price: 3500,
    city: "Paris",
    location: "Champs-Élysées",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    category: "Trending",
  },
  {
    title: "Tokyo Neon Apartment",
    description: "A bright, modern apartment in the lively Shinjuku district of Tokyo.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd",
    },
    price: 2200,
    city: "Tokyo",
    location: "Shinjuku",
    country: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    category: "Trending",
  },
  {
    title: "Sydney Harbour Escape",
    description: "Enjoy waterfront luxury with incredible views of the Sydney Opera House.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759",
    },
    price: 2800,
    city: "Sydney",
    location: "Darling Harbour",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    category: "Trending",
  },
  {
    title: "Seaside Retreat in Cape Town",
    description: "Wake up to breathtaking ocean views and enjoy world-class beaches minutes away.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523731407965-2430cd12f5e4",
    },
    price: 1600,
    city: "Cape Town",
    location: "Camps Bay",
    country: "South Africa",
    latitude: -33.9249,
    longitude: 18.4241,
    category: "Trending",
  },
  {
    title: "Seoul Modern Skyline Suite",
    description: "A high-rise apartment located in the vibrant district of Gangnam.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1528605248644-14dd04022da1",
    },
    price: 2600,
    city: "Seoul",
    location: "Gangnam",
    country: "South Korea",
    latitude: 37.5665,
    longitude: 126.978,
    category: "Trending",
  },
  {
    title: "Minimalist Single Room",
    description: "A compact, clean single room ideal for budget travelers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    },
    price: 600,
    city: "Berlin",
    location: "Mitte",
    country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
    category: "Rooms",
  },
  {
    title: "Comfort Twin Bedroom",
    description: "A bright twin-sharing room with modern amenities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    },
    price: 700,
    city: "Toronto",
    location: "Downtown Core",
    country: "Canada",
    latitude: 43.6532,
    longitude: -79.3832,
    category: "Rooms",
  },
  {
    title: "Studio Room in City Center",
    description: "A self-contained studio room with a kitchenette and workspace.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1505691723518-36a5ac3be353",
    },
    price: 900,
    city: "Barcelona",
    location: "Eixample",
    country: "Spain",
    latitude: 41.3851,
    longitude: 2.1734,
    category: "Rooms",
  },
  {
    title: "Scenic Rooftop Room",
    description: "A peaceful rooftop room offering panoramic views of the surroundings.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    },
    price: 950,
    city: "Cape Town",
    location: "Gardens",
    country: "South Africa",
    latitude: -33.9249,
    longitude: 18.4241,
    category: "Rooms",
  },
  {
    title: "Quiet Suburban Guest Room",
    description: "A peaceful guest room located in a safe suburban neighborhood.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1590490360182-c33d57733427",
    },
    price: 500,
    city: "Melbourne",
    location: "Fitzroy",
    country: "Australia",
    latitude: -37.8136,
    longitude: 144.9631,
    category: "Rooms",
  },
  {
    title: "Luxury King Room",
    description: "A spacious king-sized bedroom offering premium bedding and facilities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    },
    price: 1400,
    city: "Rome",
    location: "Trastevere",
    country: "Italy",
    latitude: 41.9028,
    longitude: 12.4964,
    category: "Rooms",
  },
  {
    title: "Skyline Apartment Overlooking Times Square",
    description: "A modern high-rise apartment offering breathtaking skyline views in the heart of Times Square.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1534447677768-be436bb09401",
    },
    price: 3000,
    city: "New York",
    location: "Times Square",
    country: "United States",
    latitude: 40.758,
    longitude: -73.9855,
    category: "Iconic Cities",
  },
  {
    title: "Charming Studio Near Eiffel Tower",
    description: "A romantic Parisian studio just minutes away from the iconic Eiffel Tower.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    },
    price: 2800,
    city: "Paris",
    location: "7th Arrondissement",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    category: "Iconic Cities",
  },
  {
    title: "Sydney Opera Harbour View Loft",
    description: "A bright loft with panoramic views of the Sydney Opera House and Harbour Bridge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9",
    },
    price: 2900,
    city: "Sydney",
    location: "Circular Quay",
    country: "Australia",
    latitude: -33.8587,
    longitude: 151.214,
    category: "Iconic Cities",
  },
  {
    title: "Rome Colosseum View Apartment",
    description: "A historic apartment with a window view directly facing the ancient Colosseum.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
    },
    price: 2700,
    city: "Rome",
    location: "Centro Storico",
    country: "Italy",
    latitude: 41.8902,
    longitude: 12.4922,
    category: "Iconic Cities",
  },
  {
    title: "Hong Kong Victoria Peak Skyline Suite",
    description: "Experience the world's most iconic skyline from a high-altitude luxury suite.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    },
    price: 3600,
    city: "Hong Kong",
    location: "Victoria Peak",
    country: "China",
    latitude: 22.2758,
    longitude: 114.1455,
    category: "Iconic Cities",
  },
  {
    title: "Cozy Cabin in the Himalayas",
    description: "A wooden cabin surrounded by snow-capped peaks and stunning views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 1100,
    city: "Manali",
    location: "Old Manali",
    country: "India",
    latitude: 32.2432,
    longitude: 77.1892,
    category: "Hill Stations",
  },
  {
    title: "Swiss Alpine Chalet",
    description: "An elegant chalet nestled in the Swiss Alps, perfect for a peaceful escape.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    },
    price: 3200,
    city: "Zermatt",
    location: "Gornergrat Valley",
    country: "Switzerland",
    latitude: 46.0207,
    longitude: 7.7491,
    category: "Hill Stations",
  },
  {
    title: "Canadian Rockies Lodge",
    description: "Experience pristine mountain views in this beautiful Canadian lodge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb",
    },
    price: 1800,
    city: "Banff",
    location: "Tunnel Mountain",
    country: "Canada",
    latitude: 51.1784,
    longitude: -115.5708,
    category: "Hill Stations",
  },
  {
    title: "Kashmir Valley Retreat",
    description: "A serene retreat located in the lush valleys of Kashmir with breathtaking views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    },
    price: 1500,
    city: "Gulmarg",
    location: "Strawberry Valley",
    country: "India",
    latitude: 34.0484,
    longitude: 74.3805,
    category: "Hill Stations",
  },
  {
    title: "Bhutan Hillside Cottage",
    description: "A peaceful cottage located amidst the rolling hills of Bhutan.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    },
    price: 1400,
    city: "Paro",
    location: "Paro Valley",
    country: "Bhutan",
    latitude: 27.4305,
    longitude: 89.4136,
    category: "Hill Stations",
  },
  {
    title: "Nepal Himalayan Eco Lodge",
    description: "Stay close to the Annapurna mountain range in this eco-friendly lodge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb",
    },
    price: 1300,
    city: "Pokhara",
    location: "Lakeside",
    country: "Nepal",
    latitude: 28.2096,
    longitude: 83.9856,
    category: "Hill Stations",
  },
  {
    title: "Highland Stone Castle",
    description: "A historic Scottish castle surrounded by misty hills and ancient forests. Perfect for royal-style retreats.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1529400971008-f566de0e6dfc",
    },
    price: 4500,
    city: "Inverness",
    location: "Highland Countryside",
    country: "United Kingdom",
    latitude: 57.4778,
    longitude: -4.2247,
    category: "Castles",
  },
  {
    title: "Bavarian Royal Castle Stay",
    description: "A luxurious Bavarian castle inspired by classic European architecture with mountain scenery.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    },
    price: 6000,
    city: "Schwangau",
    location: "Bavarian Alps",
    country: "Germany",
    latitude: 47.5576,
    longitude: 10.7498,
    category: "Castles",
  },
  {
    title: "French Countryside Chateau",
    description: "A beautifully preserved estate featuring vineyards, fountains, and historic French charm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f",
    },
    price: 4300,
    city: "Bordeaux",
    location: "French Countryside",
    country: "France",
    latitude: 44.8378,
    longitude: -0.5792,
    category: "Castles",
  },
  {
    title: "Portuguese Coastal Castle",
    description: "A seaside castle offering warm Mediterranean breezes and historic Portuguese architecture.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1551632811-561732d1e306",
    },
    price: 4200,
    city: "Porto",
    location: "Northern Coastline",
    country: "Portugal",
    latitude: 41.1579,
    longitude: -8.6291,
    category: "Castles",
  },
  {
    title: "Desert Mirage Pool Retreat",
    description: "A luxury villa in the middle of the desert featuring a reflective pool that blends with the horizon.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    },
    price: 6000,
    city: "Dubai",
    location: "Al Marmoom Desert",
    country: "United Arab Emirates",
    latitude: 25.2048,
    longitude: 55.2708,
    category: "Amazing Pools",
  },
  {
    title: "Jungle Hidden Lagoon Villa",
    description: "A private villa with a natural-style pool surrounded by lush rainforest and waterfalls.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1564078516393-cf04bd966897",
    },
    price: 3200,
    city: "Ubud",
    location: "Sacred Forest Zone",
    country: "Indonesia",
    latitude: -8.5069,
    longitude: 115.2624,
    category: "Amazing Pools",
  },
  {
    title: "Greek Cliffside Blue Pool House",
    description: "A whitewashed villa with a turquoise infinity pool overlooking the blue Mediterranean Sea.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    },
    price: 4700,
    city: "Santorini",
    location: "Oia Cliffside",
    country: "Greece",
    latitude: 36.461,
    longitude: 25.375,
    category: "Amazing Pools",
  },
  {
    title: "Luxury Caribbean Pool Estate",
    description: "A sprawling private estate with a giant curved pool surrounded by palm trees and soft ocean winds.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994",
    },
    price: 7200,
    city: "Nassau",
    location: "Paradise Island",
    country: "Bahamas",
    latitude: 25.0478,
    longitude: -77.3554,
    category: "Amazing Pools",
  },
  {
    title: "Modern Glass Pool Penthouse",
    description: "A futuristic penthouse featuring a full-glass transparent pool extending from the balcony.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    },
    price: 6500,
    city: "Los Angeles",
    location: "Hollywood Hills",
    country: "United States",
    latitude: 34.1177,
    longitude: -118.352,
    category: "Amazing Pools",
  },
  {
    title: "Forest Spa Pool Lodge",
    description: "A peaceful wooden lodge featuring a geothermal pool surrounded by forest mist.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    },
    price: 3000,
    city: "Reykholt",
    location: "Húsafell Forest",
    country: "Iceland",
    latitude: 64.699,
    longitude: -21.2956,
    category: "Amazing Pools",
  },
  {
    title: "Rainforest Pool Oasis",
    description: "A uniquely designed villa featuring a lagoon-style pool completely immersed in nature.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586105251261-72a756497a11",
    },
    price: 3500,
    city: "Cairns",
    location: "Daintree Rainforest",
    country: "Australia",
    latitude: -16.9186,
    longitude: 145.7781,
    category: "Amazing Pools",
  },
  {
    title: "Hillside Heated Pool Cabin",
    description: "A cozy hillside cabin with a heated outdoor pool overlooking snow-covered peaks.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    },
    price: 2900,
    city: "Zermatt",
    location: "Matterhorn Valley",
    country: "Switzerland",
    latitude: 46.0207,
    longitude: 7.7491,
    category: "Amazing Pools",
  },
  {
    title: "Countryside Dairy Farm Stay",
    description: "Stay on a working dairy farm with open fields, friendly cows, and fresh milk served every morning.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500595046743-cd271d694d30",
    },
    price: 900,
    city: "Ludhiana",
    location: "Village Farmlands near Mullanpur",
    country: "India",
    latitude: 30.9,
    longitude: 75.8573,
    category: "Farms",
  },
  {
    title: "Lavender Fields Farm Cottage",
    description: "A small stone cottage set in fragrant lavender fields, perfect for slow walks and golden-hour photography.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
    },
    price: 2100,
    city: "Provence",
    location: "Plateau de Valensole Farmlands",
    country: "France",
    latitude: 43.8386,
    longitude: 5.9859,
    category: "Farms",
  },
  {
    title: "Rustic Olive Farm Retreat",
    description: "Stay in a farmhouse surrounded by ancient olive trees, stone terraces, and peaceful Mediterranean views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef",
    },
    price: 2300,
    city: "Tuscany",
    location: "Chianti Countryside Estate",
    country: "Italy",
    latitude: 43.582,
    longitude: 11.318,
    category: "Farms",
  },
  {
    title: "Grape Harvest Farmstay",
    description: "Join the grape harvest, learn basic winemaking, and stay in a charming farmhouse overlooking the valley.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518998053901-5348d3961a04",
    },
    price: 1900,
    city: "Cape Town",
    location: "Stellenbosch Wine Farms",
    country: "South Africa",
    latitude: -33.9321,
    longitude: 18.8602,
    category: "Farms",
  },
  {
    title: "Summit Ridge Basecamp",
    description: "High-altitude camping with breathtaking panoramic views of the Rocky Mountains. Ideal for experienced hikers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d",
    },
    price: 120,
    city: "Estes Park",
    location: "Rocky Mountain National Park",
    country: "United States",
    latitude: 40.3428,
    longitude: -105.6836,
    category: "Camping",
  },
  {
    title: "Mystic Forest Yurt",
    description: "A cozy, circular yurt nestled in the foggy woodlands. Features a wood-burning stove and skylight for stargazing.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7",
    },
    price: 250,
    city: "Cornwall",
    location: "Bodmin Moor",
    country: "United Kingdom",
    latitude: 50.5562,
    longitude: -4.6192,
    category: "Camping",
  },
  {
    title: "Patagonian Eco-Dome",
    description: "Sustainable geodesic domes offering luxury glamping right in the heart of Torres del Paine. Unmatched mountain views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1510312305653-8ed496efae75",
    },
    price: 850,
    city: "Torres del Paine",
    location: "Magallanes Region",
    country: "Chile",
    latitude: -50.9423,
    longitude: -73.4068,
    category: "Camping",
  },
  {
    title: "Lakeside Canoe Camp",
    description: "Accessible only by canoe, this secluded spot on a private island offers total isolation and fishing opportunities.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1537225228614-56cc3556d7ed",
    },
    price: 150,
    city: "Huntsville",
    location: "Algonquin Provincial Park",
    country: "Canada",
    latitude: 45.5534,
    longitude: -78.5991,
    category: "Camping",
  },
  {
    title: "Fjord Edge Camp",
    description: "Pitch your tent on the grassy banks of a dramatic fjord. Watch waterfalls cascade down the cliffs opposite your site.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4",
    },
    price: 200,
    city: "Geiranger",
    location: "Geirangerfjord",
    country: "Norway",
    latitude: 62.1008,
    longitude: 7.2059,
    category: "Camping",
  },
  {
    title: "Desert Bloom Glamping",
    description: "Springtime camping among wildflowers. Spacious bell tents with real beds and solar power.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1496080174650-637e3f22fa03",
    },
    price: 320,
    city: "Moab",
    location: "Canyonlands",
    country: "United States",
    latitude: 38.5733,
    longitude: -109.5498,
    category: "Camping",
  },
  {
    title: "Alpine Lake Bivouac",
    description: "Minimalist camping spot next to a crystal clear glacial lake. Cold nights, warm fires, and bright stars.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1517824806704-9040b037703b",
    },
    price: 95,
    city: "Zermatt",
    location: "Matterhorn Base",
    country: "Switzerland",
    latitude: 45.9766,
    longitude: 7.6585,
    category: "Camping",
  },
  {
    title: "Aurora Glass Igloo",
    description: "Watch the Northern Lights from the comfort of your heated glass-roofed igloo. A once-in-a-lifetime Arctic experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7",
    },
    price: 1500,
    city: "Rovaniemi",
    location: "Lapland",
    country: "Finland",
    latitude: 66.5039,
    longitude: 25.7294,
    category: "Arctics",
  },
  {
    title: "Ice Fjord Lodge",
    description: "Overlooking the UNESCO protected Ice Fjord. Watch massive icebergs drift by from your heated terrace.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    },
    price: 800,
    city: "Ilulissat",
    location: "Disko Bay",
    country: "Greenland",
    latitude: 69.2198,
    longitude: -51.1,
    category: "Arctics",
  },
  {
    title: "Icelandic Lava Cabin",
    description: "Black timber cabin situated on a mossy lava field. Near the Blue Lagoon and volcanic craters.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476610182048-b716b8518aae",
    },
    price: 450,
    city: "Grindavík",
    location: "Reykjanes Peninsula",
    country: "Iceland",
    latitude: 63.8424,
    longitude: -22.4331,
    category: "Arctics",
  },
  {
    title: "Denali Tundra Camp",
    description: "Deep wilderness camp at the base of North America's highest peak. Accessible only by bush plane.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1516466723877-e4ec1d736c8a",
    },
    price: 1100,
    city: "Denali Park",
    location: "Alaska Range",
    country: "United States",
    latitude: 63.1148,
    longitude: -151.1926,
    category: "Arctics",
  },
  {
    title: "Lofoten Fisherman Cabin",
    description: "Traditional red 'Rorbu' cabin stilted over the Arctic ocean. Famous for dramatic peaks and northern lights.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86",
    },
    price: 380,
    city: "Reine",
    location: "Lofoten Islands",
    country: "Norway",
    latitude: 67.9333,
    longitude: 13.0833,
    category: "Arctics",
  },
  {
    title: "Atacama Stargazer Adobe",
    description: "Mud-brick lodge in the driest desert on Earth. Perfect for astronomy enthusiasts due to zero light pollution.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    },
    price: 550,
    city: "San Pedro de Atacama",
    location: "Atacama Desert",
    country: "Chile",
    latitude: -22.9087,
    longitude: -68.1997,
    category: "Deserts",
  },
  {
    title: "Joshua Tree Modern",
    description: "Architectural masterpiece hidden among the boulders and cacti. Outdoor shower and cowboy tub included.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504198266287-1659872e6590",
    },
    price: 700,
    city: "Joshua Tree",
    location: "Mojave Desert",
    country: "United States",
    latitude: 34.1347,
    longitude: -116.3131,
    category: "Deserts",
  }
];